version: 2

references:
  set_variables: &set_variables
    run:
      name: set_variables
      command: |
        echo 'export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}' >> ${BASH_ENV}
        echo 'export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' >> ${BASH_ENV}
        echo 'export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}' >> ${BASH_ENV}
        echo 'export dockerpass=${dockerpass}'>>${BASH_ENV}
        echo 'export dockerpass=${dockerpass}>>${BASH_ENV}'

jobs:
  build-docker-image&docker-push:
    docker:
      - image: luther007/cynerge_images:latest
    steps:
      - checkout
      - *set_variables
      - run: docker login -u="${dockeruser}" -p="${dockerpass}"
      - run: docker build -t chasecynerge/nginx:2.0
      - run: docker push chasecynerge/nginx:latest
  
   
  update-deployment-with-docker-image:
    docker:
      - image: luther007/cynerge_images:latest
    steps: 
      - checkout
      - *set_variables
      - run: aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name=cynerge
      - run: kubectl set image deployment/chase-pipeline  nginx=chasecynerge:latest--record --namespace=chase

workflows:
  version: 2
  update-deployment:
    jobs:
    - build-docker-image&docker-push
    - update-deployment-with-docker-image:
        requires:
        - build-docker-image&docker-push